### ISSUE TITLE
[11+] Premium Days

### ISSUE THREAD

**Issue by 397821** [Znote/ZnoteAAC#311]
i have a problem with premium days, when i login with client 10, the server save 'lastday' at database->accounts.
but when i login with client 11 using znote login.php, not save account -> lastday, the value continues zero. if not save 'lastday', the premium days not be removed.

the problem is login.php or server?
thankyou so much

**Comment by Znote** [comment]
Hmm, if lastday is something that gets updated on the login server in TFS, then I guess it should be added in login.php as well. 

Could also be that I need to improve the add premium days shop functionality to calculate the lastday column in the db. The question is which distributions has this, only TFS 1.0+?

**Comment by EPuncker** [comment]
@Znote 2017... xD seems like it has been fixed already with the many changes done on login.php, no? I think this can be closed

**Comment by Znote** [comment]
Not before we confirm it's fixed :p

**Comment by vagnerkuntz** [comment]
problem confirmed, so what I tested is really the 'lastday', tested with the most current version of otbr

**Comment by Znote** [comment]
So if I understand correctly, I give myself some days of premium through Znote AAC shop, which updates the "premdays" column in accounts table, and that works nicely:
![image](https://user-images.githubusercontent.com/1552144/97786458-fcd35d00-1bab-11eb-96bf-cfb069790490.png)

However, since AAC does not configure the `lastday` column, premium is infinite? (never runs out)?

I can fix this on the AAC, but this is a bit of a lost opportunity to otservbr team, they could make so if lastday == 0 and premdays == 7, then they configure lastday on login. That way, you buy premium on shop, but you activate it when you login. 

But I'll patch it.

**Comment by Znote** [comment]
@vagnerkuntz Should be fixed now.
