### ISSUE TITLE
login 12.20+/12.30 using email instead of username

### ISSUE THREAD

**Issue by joao-blip** [Znote/ZnoteAAC#424]
does your login work for customers using email and password?
tested on some it didn't work

**Comment by Znote** [comment]
Where can I download this client to test, and are you using latest otservbr-global/develop server? (or link to the one you use)

The client I currently got doesn't seem to have email login:
![image](https://user-images.githubusercontent.com/1552144/85432697-a150ed00-b583-11ea-9601-5307ada31f3f.png)

**Comment by joao-blip** [comment]
https://mega.nz/file/7ip32B5T#uHrJwJWiMu6fLNtNqPHDdMdt2P8BUwmWMnCqYZnjIDg
Cliente 12.20 

pulls 
https://github.com/opentibiabr/otservbr-global/pull/1381
https://github.com/opentibiabr/otservbr-global/pull/1380
https://github.com/FakeShinoda/otservbr-global/pull/3

**Comment by jlcvp** [comment]
I've done a MyAac plugin, you can use it as a base to get the JSON structure needed

https://github.com/OTG-Developers/myaac-tibia12-login

**Comment by Znote** [comment]
Works now. :)

![image](https://user-images.githubusercontent.com/1552144/85913289-afc53000-b833-11ea-91e4-19f3c8a88f1f.png)

But I'm still missig 12.40 client to test. Client 12.20 seems to crash on OTG server. 

I also see a potential problem:
Protocol 12.20 by FakeShinoda uses sessionKey Email, while OTG and SaiyansKing use sessionKey username. We need to agree on a consistent standard for authenticating user that connects to gameworld. 

For now I have added email sessionkey, because otservbr with 12.20 PR was the only thing that actually compiled and worked properly with my client. (OTG crashes my client, SaiyansKing didnt compile on Linux).
